pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'
        DOCKERHUB_USERNAME    = 'vinaymanjunath30'
        FRONTEND_IMAGE        = 'frontend-app'
        BACKEND_IMAGE         = 'backend-app'
    }

    stages {


        stage('Set Environment') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'dev') {
                        ENV_NAME = 'dev'
                    } else if (env.BRANCH_NAME == 'staging') {
                        ENV_NAME = 'staging'
                    } else {
                        ENV_NAME = 'prod'
                    }

                    env.IMAGE_TAG = "v1.0.${BUILD_NUMBER}-${ENV_NAME}"

                    echo "Branch: ${env.BRANCH_NAME}"
                    echo "Environment: ${ENV_NAME}"
                    echo "Image Tag: ${IMAGE_TAG}"
                }
            }
        }

        stage('Build') {
            steps {
                sh 'chmod +x jenkins/scripts/build.sh'
                sh 'jenkins/scripts/build.sh'
            }
        }

        stage('Test') {
            steps {
                sh 'chmod +x jenkins/scripts/test.sh'
                sh 'jenkins/scripts/test.sh'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonar-scanner'
                    withSonarQubeEnv('sonarqube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                          -Dsonar.projectKey=fullstack-devops \
                          -Dsonar.projectName=Fullstack-DevOps-CI \
                          -Dsonar.sources=frontend,backend \
                          -Dsonar.exclusions=**/node_modules/**,**/*.spec.js
                        """
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                sh """
                docker build -t ${DOCKERHUB_USERNAME}/${FRONTEND_IMAGE}:${IMAGE_TAG} frontend
                docker build -t ${DOCKERHUB_USERNAME}/${BACKEND_IMAGE}:${IMAGE_TAG} backend
                """
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh """
                mkdir -p /var/lib/jenkins/tmp
                export TMPDIR=/var/lib/jenkins/tmp

                trivy image --exit-code 1 --severity CRITICAL ${DOCKERHUB_USERNAME}/${FRONTEND_IMAGE}:${IMAGE_TAG}
                trivy image --exit-code 1 --severity CRITICAL ${DOCKERHUB_USERNAME}/${BACKEND_IMAGE}:${IMAGE_TAG}
                """
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: DOCKERHUB_CREDENTIALS,
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'chmod +x jenkins/scripts/docker-push.sh'
                    sh 'jenkins/scripts/docker-push.sh'
                }
            }
        }

        stage('Update Helm values') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USERNAME',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh """
                    git remote set-url origin https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/vinaymanjunath2001/multibranch-fullstack-cicd.git
                    chmod +x jenkins/scripts/update-helm-values.sh
                    BRANCH_NAME=${env.BRANCH_NAME} IMAGE_TAG=${IMAGE_TAG} jenkins/scripts/update-helm-values.sh
                    """
                }
            }
        }
    }

    post {

        always {
            sh 'docker image prune -f'
        }
        success {
            echo 'CI Pipeline completed successfully'
        }
        failure {
            echo 'CI Pipeline failed'
        }
    }
}
